# Generated by Django 2.1.2 on 2018-10-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderunner', '0002_auto_20181008_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Questions', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='submissions',
            options={'verbose_name': 'Submissions', 'verbose_name_plural': 'Submissions'},
        ),
    ]
