# Generated by Django 2.1.2 on 2018-10-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderunner', '0004_auto_20181008_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='score',
            field=models.IntegerField(default=10),
        ),
    ]
