# Generated by Django 2.1.2 on 2018-10-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderunner', '0005_questions_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='testcase1_input',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='testcase1_output',
        ),
        migrations.AddField(
            model_name='questions',
            name='run_testcase1_input',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='run_testcase1_output',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='submit_testcase1_input',
            field=models.TextField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='submit_testcase1_output',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='submit_testcase2_input',
            field=models.TextField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='submit_testcase2_output',
            field=models.TextField(default=True),
        ),
    ]
