# Generated by Django 2.1.2 on 2018-10-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderunner', '0006_auto_20181008_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='run_testcase1_input',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='run_testcase1_output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='submit_testcase1_input',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='submit_testcase1_output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='submit_testcase2_input',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='submit_testcase2_output',
            field=models.TextField(),
        ),
    ]
