# Generated by Django 2.1.2 on 2018-10-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderunner', '0008_questions_timeout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='submiited_snippet',
            new_name='submitted_snippet',
        ),
    ]
