# Generated by Django 2.1.2 on 2018-10-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderunner', '0012_auto_20181010_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='run_testcase1_input',
            field=models.TextField(max_length=50),
        ),
    ]
